### ISSUE TITLE
tao编译

### ISSUE THREAD

**Issue by jackerlu** [leesper/tao#11]
兄弟，你这个tao项目要怎么编译运行起来啊，我好像没有看到编译步骤介绍

**Comment by leesper** [comment]
兄弟，你直接到examples目录下面，随便挑一个你喜欢的，比如chat，进到server和client子目录分别go build就可以了，go语言编译就这么简单 (๑•̀ㅂ•́)و✧

**Comment by jackerlu** [comment]
不知道为什么，编译的时候出现 cannot find package "github.com/leesper/tao/examples/chat" in any of:
        /home/jacker/golang/go/src/pkg/github.com/leesper/tao/examples/chat (from $GOROOT)
        /home/jacker/golang/workspace/Go/src/github.com/leesper/tao/examples/chat (from $GOPATH)，兄弟看方便留下qq或者其他联系方式么

**Comment by jackerlu** [comment]
不知道为什么，编译的时候出现 cannot find package "github.com/leesper/tao/examples/chat" in any of:
        /home/jacker/golang/go/src/pkg/github.com/leesper/tao/examples/chat (from $GOROOT)
        /home/jacker/golang/workspace/Go/src/github.com/leesper/tao/examples/chat (from $GOPATH)，兄弟看方便留下qq或者其他联系方式么

**Comment by leesper** [comment]
哥，你GOPATH配置对了吗？如果对了，不应该啊
