### ISSUE TITLE
协议的问题

### ISSUE THREAD

**Issue by byteman** [leesper/tao#13]
请问你们在实际在产品里面也是用的 type-length-data 这种方式吗？没有使用校验或者同步之类的字段吗？ 如果数据错位的话，会不会一直就取不到正确的数据，虽然tcp是流的方式，有这种可能性的存在吗？

**Comment by leesper** [comment]
你好，我们产品里面用的就是这种格式。只要大家都遵循相同的模式，取不到数据的情况我觉得应该不会有。我之前从事过Java的手游服务端开发，当时那个网络编程框架就是这么做的。 @byteman
