### ISSUE TITLE
服务如何stop

### ISSUE THREAD

**Issue by piaohailin** [leesper/tao#14]
没有优雅的stop方式吗？都是用sh的kill方式吗？如果是这样会不会产生数据不完整的情况？

**Comment by leesper** [comment]
kill的时候，你可以用channel监听信号量，一旦chan从阻塞态返回，你就可以调用Stop()了，例如：
```
go func() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)
		<-c
		chatServer.Stop()
	}()
```

**Comment by leesper** [comment]
@piaohailin 还有我在writeLoop里都是把积攒的请求发送完毕之后再退出的，这个也能减少数据包未发送完就退出的情况发生。

**Comment by piaohailin** [comment]
这种方法就是部署的时候把服务切到后台运行，stop的时候在切到前台用控制台命令stop。
