### ISSUE TITLE
msgType 取值问题。

### ISSUE THREAD

**Issue by piaohailin** [leesper/tao#15]
我理解是每一组序列化协议就要定义一个ID，例如：项目中有两组序列化协议。一组序列化协议是处理二进制的这时ID=1，同时还有一组协议处理字符串序列化这时ID=2；这是正确的使用方法吧？还有其他最佳实践吗？

**Comment by leesper** [comment]
恩恩，我是模仿之前我做手游服务端时的方式，即每个协议（无论是请求还是响应）都带有一个msgType，以此来区分是哪个协议。
