### ISSUE TITLE
Tao框架写是server端报错？请问这是什么情况？

### ISSUE THREAD

**Issue by robinbing123456** [leesper/tao#17]
用的花生壳，连接电脑连的是我的本机

测试方法一、通过串口服务器工具测试服务器端可以接收数据
15:42:53 收到数据：~~~~64888672247000001590041095500000

测试方法二、自己从网上找的程序server 也没问题

测试方法三、自己写的client端用tao框架写的server端也是可以收到数据

测试方法四、只用tao框架写server端接收不到数据直接报2017/07/19 15:20:09 ERROR [tao.TypeLengthValueCodec.Decode] (message.go:197) - message(type 2122219134) has bytes(943207478) beyond max 8388608
2017/07/19 15:20:09 ERROR [tao.readLoop] (conn.go:604) - error decoding message more than 8M data

**Comment by leesper** [comment]
自己写个Codec吧，不要用框架里的

**Comment by robinbing123456** [comment]
框架里面没有做处理吗？

**Comment by leesper** [comment]
@robinbing123456 我写的这个Codec是用来解决我自己的问题的哈，你要是觉得不好用，自己写一个，还好我预留了接口

**Comment by robinbing123456** [comment]
package main

import (
    //"bytes"
    "fmt"
    "io"
    "math/rand"
    "net"
    "os"
    "time"
)

func checkError(err error) {
    if err != nil {
        fmt.Fprintf(os.Stderr, "Fatal error: %s", err.Error())
        os.Exit(1)
    }
}

func main() {
    ln, err := net.Listen("tcp", "127.0.0.1:1987")
    checkError(err)

    for {
        conn, err := ln.Accept()
        if err != nil {
            fmt.Fprintf(os.Stderr, "Fatal error: %s", err.Error())
            continue
        }
        go run(conn)

    }
}

func run(conn net.Conn) {
    var all_len int = 0
    buffer := make([]byte, 1024)
    rand.Seed(time.Now().Unix())
    filename := string(rand.Intn(100))
    writeFile, err := os.OpenFile(filename, os.O_RDWR|os.O_APPEND|os.O_CREATE, 0777)
    if err != nil {
        fmt.Println("create file error:", filename, err)
        return
    }
    defer writeFile.Close()
    for {

        lenght, err := conn.Read(buffer)
        if err != nil {
            if err == io.EOF {
                break
            }
            fmt.Fprintf(os.Stderr, "read buff error: %s", err.Error())
            return
        }
        fmt.Println("receive data lenght:", lenght)

        //_, err = writeFile.Write(buffer[:bytes.Index(buffer[:], []byte{0})])
        _, err = writeFile.Write(buffer[:lenght])
        if err != nil {
            fmt.Println("write file error", err)
            return
        }

        all_len += lenght

    }
    fmt.Println("write file done", all_len/1024/1024)
    return
}



用框架不能实现我上面的这个吗？

**Comment by robinbing123456** [comment]
他每次发的都很小不会超过1M，当他再执行tao框架里面注册方法里的第二个参数那里好像到那里不走了然后跑了差不多1分钟就才报超过8M，这是什么原因呢？

**Comment by robinbing123456** [comment]
他隔一分钟打印一次，而且始终都是停留到那个方法那里，也不能打印log

**Comment by robinbing123456** [comment]
还在吗？
