### ISSUE TITLE
几个疑点麻烦解答

### ISSUE THREAD

**Issue by railsfans** [leesper/tao#26]
最近正在学习go网络编程看到你的框架感觉还行，准备应用到项目里面去，以下是我阅读你源码的几个疑点。
1、我看你已经开放了自定义的Decode接口，能否提供一个example供我参考一下。（优先级低些，因为我的通讯协议跟你一样）
2、我的业务里面需要对每个会话定时轮询以处理一些业务，比如定时检查是否需要主动向某个会话推送内容。能否给个例子。
3、长连接关闭问题，我看之前有个issue已经提过这个问题了，但是我看你给的示例代码有点老了，如下
someServer.SetOnScheduleCallback(40 * time.Second, func(now time.Time, data interface{}) {
    cli := data.(tao.Connection)
    lastTimestamp := cli.GetHeartBeat()
    session, ok := cli.GetExtraData().(common.Session)
    if ok {
      timeout = session.TimeOut
    }
    if now.UnixNano() - lastTimestamp > int64(timeout) * 1e9 {
      holmes.Warn("Client %d timeout, close it\n", cli.GetNetId())
      cli.Close()
    }
})
后面SetOnScheduleCallback改成Sched这个函数名，我发现代码里面已经没了tao.Connection这个了，这段代码怎么改
tips：
刚刚学习go，可能有点菜，麻烦不吝赐教。

**Comment by leesper** [comment]
@railsfans 谢谢你对我的关注，我尽量抽空回答你的问题哈，最近刚换了工作，特别的忙，每天都工作到深夜，这个项目我是要一直维护下去的，例子确实少了，我尽量抽出时间来回答你的问题，有照顾不周的地方请谅解~

**Comment by railsfans** [comment]
非常感谢你抽空回答我的问题，这几天我也研究了你的源码，在pingpong这个例子自己动手加入定时，服务器3s时间到就直接退出了，没起到循环定时的功能，不知道什么原因，代码如下
server := NewPingPongServer()
server.Sched(3 * time.Second, func(now time.Time, cli tao.WriteCloser) {
    holmes.Fatalln("Client timeout") 
 })
server.Start(l)
出现的打印
2018/07/30 19:00:54 FATAL [main.main.func1] (server.go:55) - Client timeout
exit status 1

**Comment by leesper** [comment]
@railsfans 
1. holmes.Fatalln表示打印致命错误，因此会调用系统的exit强制退出，这是你没有循环的原因；
2. Decode这个接口，你可以看看message.go里面的TypeLengthValueCodec这个struct，它就是对这个接口的实现；
3. tao.Connection现在叫WriteCloser，我重新按照Go语言的方式设计了接口

其实这个库我一直有计划继续改进的，无奈刚转行做大数据软件工程师，现在里里外外忙得一塌糊涂，一直都找不到时间来搞，我主要想用反射来优化下协议的注册，然后重新设计一下定时器什么的

**Comment by railsfans** [comment]
非常感谢你的回答，今天我调试的时候突然发现你的holmes这样使用有点问题，
package main
import "github.com/leesper/holmes"

func main() {
  // log files put in ./log, create new one every hour, also print to stdout
  defer holmes.Start(LogFilePath("./log"), EveryHour, AlsoStdout).Stop()
  holmes.Infof("%s", "If by life you were deceived,")
  holmes.Warnf("%s", "Don't be dismal, don't be wild!")
  holmes.Errorf("%s", "In the day of grief, be mild.")
  holmes.Infof("%s", "Merry days will come, believe.")
}
错误如下：
./debug.go:6:22: undefined: LogFilePath
./debug.go:6:44: undefined: EveryHour
./debug.go:6:55: undefined: AlsoStdout

**Comment by railsfans** [comment]
上面的例子我知道原因了，需要在每个变量面前加上holmes，比如holmes.LogFilePath这样就没问题了，你的holmes这边需要更新一下例子，要不然可能会误导新手。
另外请教你一下因为我的业务里面需要设置上线时间和离线时间，我看了下NewGoServer的onConnect，onClose函数正好对应，但是这两个函数返回的conn tao.WriteCloser对我来说没有意义，我需要这个连接的netid或者name，我试下了在函数里面打印conn.NetId()或者conn.Name()都错误，请问下怎么才能获取这个值。
type ServerConn struct {
netid   int64
name    string
 ...
}

func NewGoServer() *GoServer {
  onConnect := tao.OnConnectOption(func(conn tao.WriteCloser) bool {
    holmes.Infoln("on connect"，conn.Name()) //这样会错，想获取这个连接的netid怎么改
    return true
  })
  onClose := tao.OnCloseOption(func(conn tao.WriteCloser) {
    holmes.Infoln("on close"，conn.Name()) //这样会错，想获取这个连接的netid怎么改
  })
  return &GoServer{ 
    tao.NewServer(onConnect，onClose),
  }
}
