### ISSUE TITLE
对于里面的concurrent map，如何在遍历中删除元素？

### ISSUE THREAD

**Issue by Glacier759** [leesper/tao#4]
for iter := range cMap.IterKeys() {
     cMap.Remove(iter)
}
这样做将会死锁，，

**Comment by leesper** [comment]
嗯嗯，我也发现这个问题了，所以我在util.go里面写了一个ConnectionMap来管理客户端连接，它其实就是map加读写锁，所以效率较低。ConcurrentMap因为有死锁的bug，暂时没有使用，Github上有个项目[go-concurrentMap](https://github.com/fanliao/go-concurrentMap)，是高仿Java的ConcurrentHashMap，从测试数据来看效率非常高，如果你感兴趣可以看下，但实现很复杂，几乎是将Java的实现搬到Go来了，因为两种语言的内存模型不太一样，我没敢搬过来直接用，ConcurrentMap我还没来得及改，sorry

**Comment by leesper** [comment]
我能想到的一个折中的方法，就是先IterKeys()把所有的key遍历一遍，放到slice中，然后遍历slice，再逐个删除
