### ISSUE TITLE
用Go实现异步真的有必要吗？

### ISSUE THREAD

**Issue by xgfone** [leesper/tao#5]
据我所知，其它语言实现异步的主要原因是其并发性能太差（究其原因是进程、线程都太重了），比如：JS和Java的异步IO，有一些语言开始支持协程（如JS、Python等）——可认为是更加轻量级且自动实现同步锁的线程。之所以开始流行协程，其中之一就是异步太复杂（看看JS，一步一步在朝着同步方向走，JS7标准开始内建协程—— `async` 和 `await`），否则大家都用异步得了。

我们公司五年前开发的软件架构，用异步，甚至令人胆寒到一个TCP应答请求居然拆成了两个TCP连接@_@，现在改起来都很难。如果现在谁在这样设计（即把一个TCP请求拆成两个连接），真想一口唾沫淹死他！

而 Go 用 goroutine 实现了协程，但又与原始的协程不同：原始的协程要求协程之间能自动实现同步锁，这样的结果就是不能同一时间利用多核（即并行，非并发）。另外，Go的理念是：`不要通过共享内存来通信，而是通过通信来共享内存`。因此，Go中的 goroutine 并没有实现同步锁，这由用户自己实现。

在 Go 中，goroutine 是很廉价的，因此并发性很高，使用简单且是同步的。这个时候，在 Go 中再去实现异步真的还有必要吗？现在大家都在往同步方向走（哪怕底层用异步来实现同步），这个项目却是把一个不错的同步变成异步，我怎么觉得有点本末倒置呢。

以上仅是在不知道你的业务需求下的一家之言，勿怪 :)

**Comment by leesper** [comment]
哈哈哈哈哈，兄台所言即是！不过请不要被名字迷惑了，我这里所说的“异步”并不是指并发线程模型意义上的“异步”。而是指我在框架中有两个地方用了“异步”的方式来处理。Goroutine是相当轻量级的，所以我在框架中也“小奢侈”了一把——对于每一个TCP连接，我开了三个Goroutine去处理：readLoop()，writeLoop()和handleLoop()。第一个“异步”的地方是Connection的Write()调用，它只是将要发送的数据包放到channel里，然后由负责writeLoop()的Goroutine在稍后发送出去；第二个“异步”的地方在负责handleServerLoop()的Goroutine中，它通过hash函数将请求散列到工作者Goroutine中去处理，且保证同一个TCP连接的请求被散列到同一个工作者Goroutine，以实现按序处理请求。不知道有没有回答清楚你的疑问呢？
