### ISSUE TITLE
请教关于go实现网络库的疑问

### ISSUE THREAD

**Issue by molixiaoge** [leesper/tao#8]
自己实现过 c++ 的iocp epoll 异步网络库,最近因为c++开发效率太慢打算使用go混合编程.想写个go的tcp server和 client ,但是网上的资料都是入门级的根本没法看.而且看了之后很纳闷 goroutine对线程安全这方面主要使用哪种同步方式?
  我知道go的socket底层都是异步方式,提供上层调用时同步方式.我个人理解就是 基本上 goroutine之间都是在多线程编码了,这反而增加了开发的难度!

**Comment by leesper** [comment]
你好！我也是C++出身的程序员，C++如果你很清楚了，那么Go其实很好上手的，下面我来集中回答下你的问题。
1. goroutine对线程安全使用哪种同步方式？
用epoll搞异步IO的时候，我们都需要复用线程，因为线程虽然已经比进程轻量了，但仍然很“贵”，而且线程的数量有限制，不能想开多少开多少。我见过的一个典型的Java实现的epoll手游服务器，开了2n+1个IO线程，其中0号线程用于accept新连接，然后其中的奇数号线程用于读，偶数号线程用于写，然后还有工作者线程等等。
但是放到Go里面，Go的底层调度goroutine的时候仍然用epoll，相当于已经给你做好了，你到goroutine层面的时候其实只需要考虑两个问题：1）goroutine间的同步问题；2）数据结构的同步问题。举个例子，tao框架中对于每一个连上来的客户端都开辟了三个goroutine，readLoop负责（同步）读bytes data，交给codec解析成message；writeLoop负责将获取的message序列化成bytes data，然后write出去；handlerLoop负责根据message找到对应的回调（通过协议号），然后调用这个回调函数处理message。这三个goroutine都是main goroutine开辟的，那么关闭连接的时候如何优雅地关闭这三个goroutine并告诉main就是需要注意的，比如writeLoop需要先发送完全部数据再退出，readLoop停止再读取任何数据等等，这里goroutine之间的同步主要通过sync标准库实现，特别是sync.WaitGroup。main每开辟一个goroutine就WaitGroup.Add()一下，完成开辟工作后main会调用WaitGroup.Wait()阻塞等待，而开辟的goroutine在退出前调用WaitGroup.Done()报告自己“使命已经结束”，当所有的子goroutine都Done()完了，前面那个阻塞等待的main就会唤醒然后继续向下执行。
至于数据结构的同步问题，Go语言标准库中的数据结构都不是线程安全的，需要自己简单加工一下，比如使用sync.RWMutex读写锁。tao框架中有一个管理客户端连接的map，就是使用读写锁加工过的并发数据结构，因为多个线程都会读写这个数据结构，还有就是定时器timer，它内部使用的是小顶堆来管理定时任务，定时任务可取消可添加，所有的客户端连接都要对它进行操作，所有它也必须是线程安全的，这里采用的是另一种方法：使用Go语言强大的channel机制，把所有对堆数据结构的操作都放到channel中形成一个队列，然后由一个负责的线程按序处理，即“多线程操作转换成单线程处理”。
2. goroutine之间在多线程编码，这增加了开发难度？
我觉得问题1已经回答了问题2，所以这里就不再重复啦，tao框架是怎么运作的，我写的有文档，在简书上，项目主页有连接，你可以看下。另外，《The Go Programming Language》这本书相当不错，强烈推荐。

**Comment by molixiaoge** [comment]
好的 谢谢你的解答!剩下的我要做的就是习惯goroutine 通信开发了.
