### ISSUE TITLE
MonitorOn函数还没有实现web展示测量值吗？

### ISSUE THREAD

**Issue by byteman** [leesper/tao#9]
func MonitorOn(port int) {
	go func() {
		if err := http.ListenAndServe(fmt.Sprintf(":%d", port), nil); err != nil {
			holmes.Errorln(err)
			return
		}
	}()
}
MonitorOn函数还没有实现web展示测量值吗？我看这里只是开启了一个http服务

**Comment by leesper** [comment]
我用了另一个比较牛逼的工具，是个外国人写的

**Comment by byteman** [comment]
什么工具啊？给我分享一下啊

**Comment by leesper** [comment]
@byteman https://github.com/divan/expvarmon

**Comment by byteman** [comment]
不错不错，但是并没有可以测试QPS的选项啊

**Comment by leesper** [comment]
@byteman 老实说，我也不晓得QPS的公式是啥，但如果知道公式，应该可以从这些指标中做计算的
